import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/partials/Footer";
import { inter } from "@/hooks/fonts";
import Navbar from "@/components/partials/Navbar";
import AppWrapper from "@/components/shared/AppWrapper";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body className="bg-background">
        <Navbar />
        <AppWrapper>{children}</AppWrapper>
        <Footer />
      </body>
    </html>
  );
}
